<script setup lang="ts">
import type { ApiProblem } from '~/types/api'; import type { CourseOffering } from '~/types/domain'
const props = defineProps<{ offering?: CourseOffering }>(); const emit = defineEmits<{ saved: [offering: CourseOffering] }>(); const { get } = useLookups(); const { create, update } = useCourseOfferings(); const { data: lookups } = await useAsyncData('offering-form-lookups', get)
const form = reactive({ course_id: props.offering?.course_id ?? '', academic_term_id: props.offering?.academic_term_id ?? '', instructor_id: props.offering?.instructor_id ?? '', section: props.offering?.section ?? '', room: props.offering?.room ?? '', capacity: props.offering?.capacity ?? 30, status: props.offering?.status ?? 'open', schedules: props.offering?.schedules?.map(item => ({ day_of_week: item.day_of_week, start_time: item.start_time.slice(0, 5), end_time: item.end_time.slice(0, 5), room: item.room ?? '' })) ?? [{ day_of_week: 'monday', start_time: '08:00', end_time: '09:00', room: '' }] })
const errors = ref<Record<string, string[]>>({}); const submitting = ref(false)
function addSchedule() { form.schedules.push({ day_of_week: 'monday', start_time: '08:00', end_time: '09:00', room: '' }) }
async function submit() { errors.value = {}; submitting.value = true; try { const payload = { ...form, course_id: Number(form.course_id), academic_term_id: Number(form.academic_term_id), instructor_id: form.instructor_id ? Number(form.instructor_id) : null, capacity: Number(form.capacity) } as unknown as Partial<CourseOffering>; emit('saved', props.offering ? await update(props.offering.id, payload) : await create(payload)) } catch (error) { const problem = error as ApiProblem; errors.value = problem.errors ?? { form: [problem.message] } } finally { submitting.value = false } }
</script>
<template><form class="space-y-6" @submit.prevent="submit"><BaseCard><div class="grid gap-4 sm:grid-cols-2"><FormField for="course" label="Course" required :error="errors.course_id?.[0]"><BaseSelect id="course" v-model="form.course_id" :options="(lookups?.courses ?? []).map(item => ({ label: `${item.course_code} · ${item.course_title}`, value: item.id }))" /></FormField><FormField for="term" label="Academic term" required :error="errors.academic_term_id?.[0]"><BaseSelect id="term" v-model="form.academic_term_id" :options="(lookups?.academic_terms ?? []).map(item => ({ label: `${item.academic_year} · ${item.term.replaceAll('_', ' ')}`, value: item.id }))" /></FormField><FormField for="instructor" label="Instructor" :error="errors.instructor_id?.[0]"><BaseSelect id="instructor" v-model="form.instructor_id" :options="[{ label: 'Unassigned', value: '' }, ...(lookups?.instructors ?? []).map(item => ({ label: item.name, value: item.id }))]" /></FormField><FormField for="section" label="Section" required :error="errors.section?.[0]"><BaseInput id="section" v-model="form.section" /></FormField><FormField for="room" label="Room"><BaseInput id="room" v-model="form.room" /></FormField><FormField for="capacity" label="Capacity" required :error="errors.capacity?.[0]"><BaseInput id="capacity" v-model="form.capacity" type="number" /></FormField><FormField for="status" label="Status" required><BaseSelect id="status" v-model="form.status" :options="['open', 'closed', 'ongoing', 'completed', 'cancelled'].map(value => ({ label: value, value }))" /></FormField></div></BaseCard><BaseCard><div class="mb-4 flex justify-between"><h2 class="font-semibold">Structured schedule</h2><BaseButton variant="secondary" @click="addSchedule">Add schedule</BaseButton></div><div class="space-y-3"><div v-for="(schedule, index) in form.schedules" :key="index" class="grid gap-3 sm:grid-cols-[1fr_1fr_1fr_1fr_auto]"><BaseSelect :id="`schedule-day-${index}`" v-model="schedule.day_of_week" :options="['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'].map(value => ({ label: value, value }))" /><BaseInput :id="`schedule-start-${index}`" v-model="schedule.start_time" type="time" /><BaseInput :id="`schedule-end-${index}`" v-model="schedule.end_time" type="time" /><BaseInput :id="`schedule-room-${index}`" v-model="schedule.room" placeholder="Room" /><BaseButton variant="ghost" @click="form.schedules.splice(index, 1)">Remove</BaseButton></div></div><p v-if="errors.schedules" class="mt-3 text-sm text-red-600">{{ errors.schedules[0] }}</p></BaseCard><p v-if="errors.form" class="text-sm text-red-600">{{ errors.form[0] }}</p><div class="flex justify-end gap-3"><BaseButton to="/course-offerings" variant="secondary">Cancel</BaseButton><BaseButton type="submit" :loading="submitting" :disabled="submitting">Save offering</BaseButton></div></form></template>
