<script setup lang="ts">
import type { ApiProblem } from '~/types/api'; import type { FormFieldDefinition } from '~/types/forms'
definePageMeta({ middleware: 'auth' })
const { get } = useLookups(); const { data: lookups } = await useAsyncData('user-lookups', get)
const fields = computed<FormFieldDefinition[]>(() => [{ key: 'name', label: 'Full name', required: true }, { key: 'email', label: 'Email', required: true }, { key: 'role_id', label: 'Role', type: 'select', required: true, options: (lookups.value?.roles ?? []).map(role => ({ label: role.name, value: role.id })) }, { key: 'status', label: 'Status', type: 'select', required: true, options: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }, { label: 'Suspended', value: 'suspended' }] }, { key: 'password', label: 'Initial password', type: 'password', required: true }, { key: 'password_confirmation', label: 'Confirm initial password', type: 'password', required: true }])
const { create } = useUsers(); const { show } = useToasts(); const submitting = ref(false); const errors = ref<Record<string, string[]>>({})
async function save(values: Record<string, string | number>): Promise<void> { submitting.value = true; errors.value = {}; try { await create({ ...values, role_id: Number(values.role_id), status: String(values.status), name: String(values.name), email: String(values.email), password: String(values.password), password_confirmation: String(values.password_confirmation) }); show('User created successfully.'); await navigateTo('/users') } catch (error) { const problem = error as ApiProblem; errors.value = problem.errors ?? { form: [problem.message] } } finally { submitting.value = false } }
</script>
<template><div class="page-shell"><PageHeader title="Add user" description="Create an account with a temporary password." /><EntityForm :fields="fields" submit-label="Create user" cancel-to="/users" :submitting="submitting" :server-errors="errors" @submit="save" /></div></template>
